In [8]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [88]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Invertir el vector

In [89]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [90]:
valores = np.arange(0,9).reshape(3,3)
valores

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [91]:
ceros = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.argwhere(ceros!=0)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]], dtype=int64)

### Crear una matriz identidad de 6x6

In [92]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [93]:
azar = np.random.random((3,3,3))
azar

array([[[0.83628826, 0.97130066, 0.54837841],
        [0.77684756, 0.77374857, 0.58696621],
        [0.74134327, 0.61973926, 0.46428408]],

       [[0.10883861, 0.45517522, 0.2370647 ],
        [0.58051187, 0.88401262, 0.91940105],
        [0.701012  , 0.26003709, 0.70534357]],

       [[0.10611147, 0.4937874 , 0.10318567],
        [0.89176717, 0.30071587, 0.27604644],
        [0.38006513, 0.18181051, 0.15435376]]])

### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [94]:
print(azar.argmax())
print(azar.ravel()[azar.argmax()])

print(azar)
print(np.unravel_index(azar.argmax(), azar.shape))
azar[np.unravel_index(azar.argmax(), azar.shape)]

1
0.9713006592483185
[[[0.83628826 0.97130066 0.54837841]
  [0.77684756 0.77374857 0.58696621]
  [0.74134327 0.61973926 0.46428408]]

 [[0.10883861 0.45517522 0.2370647 ]
  [0.58051187 0.88401262 0.91940105]
  [0.701012   0.26003709 0.70534357]]

 [[0.10611147 0.4937874  0.10318567]
  [0.89176717 0.30071587 0.27604644]
  [0.38006513 0.18181051 0.15435376]]]
(0, 0, 1)


0.9713006592483185

### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [95]:
ones = np.ones((10,10))
ones[1:1-1,1:-1] = 0
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [96]:
np.tile( np.arange(0,5) , 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [52]:
cajita = np.ones((10,10))
cajita[0,9] = 9
cajita[0,0] = 9
cajita[-1,0] = 9
cajita[-1,9] = 9

cajita[0,1] = 8
cajita

array([[9., 8., 1., 1., 1., 1., 1., 1., 1., 9.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [9., 1., 1., 1., 1., 1., 1., 1., 1., 9.]])

### Crear dos arreglos al azar A y B, verificar si son iguales

In [97]:
a = np.random.random((3,3))
b = np.random.random((3,3))

a == b 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [98]:
np.allclose(a,b)

False

In [99]:
np.array_equal(a,b)

False