##### **IMPORTANDO UNA LIBRERIA NUMPY** ###### 

In [1]:
import numpy as np

##### **CREANDO UNA LISTA DE 10 ELEMENTOS** ######

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### **TRANSFORMANDO LA LISTA A UN ARRAY** #####

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### **CORROBORANDO EL TIPO DE DATO** ###### 

In [4]:
type(arreglo)

numpy.ndarray

##### **CORROBORANDO EL TIPO DE DATO DE ARREGLO** #####

In [5]:
arreglo.dtype

dtype('int32')

##### **DEFINIENDO EL ARRAY DE int32 a float32** #####

In [6]:
np.array(arreglo, dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### **SIGUE SIENDO UN ARRA DE int32** #####

In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### **TRANSFORMANDO DATOS DE int32 a float32** #####

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [9]:
arreglonew = np.arange(1,11,2)
arreglonew

array([1, 3, 5, 7, 9])

<h1 style = 'color:cyan'><b>ALGUNAS FUNCIONES DE NUMPY</b></h3>
<h4 style = 'color:aquamarine'>Obteniendo el promedio del array</h3>

In [10]:
promedio = np.mean(arreglo)
promedio

5.5

In [11]:
mediana = np.median(arreglo)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
desviacion_standard = np.std(arreglo)
desviacion_standard 

2.8722813232690143

In [13]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
arreglo_de_unos_2 = np.zeros(10)
arreglo_de_unos_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arreglo_de_unos = arreglo_de_unos.astype(int)
arreglo_de_unos 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h1 style = 'color:orange'><b>UTILIZANDO LA FUNCION RANDOM</b></h3>
<h4 style = 'color:blue'>Generando arreglo aleatorio de 5 elementos</h3>

In [16]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.43764562, 0.86313888, 0.47540301, 0.98755796, 0.42414179])

<h4 style = 'color:blue'>Generando una matriz de 3x3</h5>

In [17]:
matriz = np.random.rand(3,3)
matriz

array([[0.58161252, 0.2200634 , 0.53597691],
       [0.6467411 , 0.02279097, 0.20229423],
       [0.90244374, 0.09914459, 0.23564307]])

<h4 style = 'color:blue'>Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5</h3>

In [18]:
arreglo_aleatorio2 = np.random.rand(2,3,5)
arreglo_aleatorio2

array([[[7.55344911e-01, 6.22067386e-01, 9.27880888e-01, 2.83534958e-01,
         3.53776899e-01],
        [6.43803181e-01, 4.74921407e-01, 1.55359266e-04, 7.43366510e-01,
         3.25564928e-01],
        [6.67871170e-01, 8.28311837e-01, 3.36681934e-02, 7.72826830e-01,
         3.26739937e-02]],

       [[9.50713762e-01, 9.13365982e-01, 2.42041203e-02, 2.76887524e-01,
         5.49735438e-01],
        [5.55806931e-01, 1.74749848e-01, 1.92333113e-01, 3.13231937e-01,
         2.16991970e-01],
        [4.74583922e-01, 4.71446764e-01, 2.79334853e-01, 9.71283683e-01,
         6.96376420e-01]]])

<h4 style = 'color:blue'>Generando una matriz aleatoria de 10 numeros enteros del 1 al 100</h3>

In [19]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[30, 71, 70, 32, 68, 98, 12, 66, 59, 65, 10, 88, 99, 51, 21],
       [22, 32, 56, 55, 50, 54, 64, 43, 77, 93, 84, 23, 64, 58, 17],
       [63,  7, 41, 53, 67, 30, 25,  5, 56, 26,  3,  6, 53, 33, 53],
       [11, 57, 26,  1, 40, 35, 52, 89, 97, 29, 74, 61, 40, 14, 44],
       [49, 67, 33, 83, 69, 60, 89, 31, 74, 73, 97, 85, 79, 67, 77],
       [99, 32, 80, 14, 93,  8, 10, 96, 18, 34, 44, 68, 33, 84, 66],
       [58, 38, 95, 49,  8, 87, 66, 62, 38, 85, 66, 69, 27, 29, 74],
       [37, 36, 66, 32, 80, 79, 17, 30, 79,  9,  5,  5, 54, 92, 40],
       [59, 66, 34, 16, 53, 77, 25,  6, 10, 84, 71, 15, 31, 80,  8],
       [ 3, 52, 62, 36, 48, 25, 66, 31, 30, 25, 80, 29, 30, 83, 40],
       [56, 28,  7, 21, 27, 89,  8, 69, 93, 63, 60, 67, 56,  4, 53],
       [29, 43, 85,  4, 12, 41, 64, 74, 71, 88, 64, 96, 75,  2, 38],
       [ 6, 30, 37, 51, 49,  4, 10, 12, 15, 60, 97, 56, 50, 41,  2],
       [49, 98, 51, 13, 25, 79, 47, 84, 66, 14, 24, 64, 27,  6, 15],
       [84, 13, 87, 37, 91, 52, 71

### **IMPRIMIR NUMEROS IMPARES DEL 1 AL 100** ###

In [20]:
arreglonuevo2 = np.arange(1,100,2)
arreglonuevo2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
np.shape(arreglo)

(10,)

In [22]:
arreglo = np.random.randint(1,10,12)
arreglo

array([6, 6, 6, 6, 9, 8, 2, 5, 8, 4, 5, 1])

In [23]:
matriz = arreglo.reshape(1,12)
matriz

array([[6, 6, 6, 6, 9, 8, 2, 5, 8, 4, 5, 1]])

In [24]:
np.shape(matriz)

(1, 12)

In [25]:
print('La posicion del valor max es',arreglo.max) 

La posicion del valor max es <built-in method max of numpy.ndarray object at 0x00000202CC040390>
