##### **IMPORTANDO UNA LIBRERIA NUMPY** ###### 

In [1]:
import numpy as np

##### **CREANDO UNA LISTA DE 10 ELEMENTOS** ######

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### **TRANSFORMANDO LA LISTA A UN ARRAY** #####

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### **CORROBORANDO EL TIPO DE DATO** ###### 

In [4]:
type(arreglo)

numpy.ndarray

##### **CORROBORANDO EL TIPO DE DATO DE ARREGLO** #####

In [5]:
arreglo.dtype

dtype('int32')

##### **DEFINIENDO EL ARRAY DE int32 a float32** #####

In [6]:
np.array(arreglo, dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### **SIGUE SIENDO UN ARRA DE int32** #####

In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### **TRANSFORMANDO DATOS DE int32 a float32** #####

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [9]:
arreglonew = np.arange(1,11,2)
arreglonew

array([1, 3, 5, 7, 9])

<h1 style = 'color:snow'><b>ALGUNAS FUNCIONES DE NUMPY</b></h3>
<h4 style = 'color:aquamarine'>Obteniendo el promedio del array</h3>

In [10]:
promedio = np.mean(arreglo)
promedio

5.5

In [11]:
mediana = np.median(arreglo)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
desviacion_standard = np.std(arreglo)
desviacion_standard 

2.8722813232690143

In [13]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
arreglo_de_unos_2 = np.zeros(10)
arreglo_de_unos_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arreglo_de_unos = arreglo_de_unos.astype(int)
arreglo_de_unos 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h1 style = 'color:orange'><b>UTILIZANDO LA FUNCION RANDOM</b></h3>
<h4 style = 'color:blue'>Generando arreglo aleatorio de 5 elementos</h3>

In [16]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.04709321, 0.2666822 , 0.03319632, 0.96721536, 0.13254604])

<h4 style = 'color:blue'>Generando una matriz de 3x3</h5>

In [17]:
matriz = np.random.rand(3,3)
matriz

array([[0.27107499, 0.18914406, 0.1093811 ],
       [0.36895105, 0.44334575, 0.58720386],
       [0.17861657, 0.18224677, 0.03514688]])

<h4 style = 'color:blue'>Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5</h3>

In [18]:
arreglo_aleatorio2 = np.random.rand(2,3,5)
arreglo_aleatorio2

array([[[0.70410721, 0.22471352, 0.03545416, 0.31583132, 0.86935339],
        [0.80809896, 0.12927799, 0.48823417, 0.71009006, 0.58698373],
        [0.74541142, 0.43395577, 0.74721714, 0.04262355, 0.95820533]],

       [[0.49847715, 0.3154256 , 0.10801156, 0.12415096, 0.1839345 ],
        [0.31928698, 0.64224636, 0.31930672, 0.12045369, 0.74966613],
        [0.58928989, 0.3013237 , 0.50217434, 0.91359278, 0.70135457]]])

<h4 style = 'color:blue'>Generando una matriz aleatoria de 10 numeros enteros del 1 al 100</h3>

In [19]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[67, 95, 74, 42, 90, 89, 11, 90, 86, 72, 98, 18, 68, 80, 33],
       [37, 27, 51, 90, 36, 97, 12, 48, 63, 13, 67, 26, 62, 38, 54],
       [61, 75, 82, 80, 68, 76, 64, 38, 39, 71, 19,  8, 82, 24, 75],
       [27, 30, 86, 86, 99, 51,  1, 96,  5, 63, 37, 24, 23, 29,  3],
       [63, 26, 42, 48, 43,  1, 43, 86, 51, 40, 66, 14,  2, 20, 57],
       [60, 74, 46, 93, 14, 34, 58, 90, 94, 98, 13, 68, 95, 74, 98],
       [70, 44, 62, 50, 97, 60, 85, 23, 89, 95, 73, 90, 66,  1, 31],
       [62,  7,  7, 19, 77, 74,  6, 63, 79, 19, 65, 19, 24, 94, 48],
       [50, 82,  7, 97, 75, 68, 20, 44, 95, 14, 21, 38, 21, 30, 45],
       [67, 87, 45,  5, 56, 92, 31, 60, 58, 35, 81, 92, 27,  4, 20],
       [10, 31, 53, 70, 83, 17, 60, 52, 18, 83, 88, 65,  1, 50, 41],
       [ 8, 41, 30, 70, 11,  7, 40, 70, 28, 97, 91, 67, 53, 68, 95],
       [16, 22,  7, 10, 85, 90, 34, 51, 26, 79, 29, 32,  2, 65, 80],
       [95, 72, 98, 63, 17, 30, 11, 86, 64, 45, 26, 84, 92, 19, 93],
       [76, 52, 22, 48, 13, 11, 68

### **IMPRIMIR NUMEROS IMPARES DEL 1 AL 100** ###

In [20]:
arreglonuevo2 = np.arange(1,100,2)
arreglonuevo2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
np.shape(arreglo)

(10,)

In [22]:
arreglo = np.random.randint(1,10,12)
arreglo

array([9, 6, 1, 1, 6, 9, 4, 9, 6, 3, 1, 2])

In [23]:
matriz = arreglo.reshape(1,12)
matriz

array([[9, 6, 1, 1, 6, 9, 4, 9, 6, 3, 1, 2]])

In [24]:
np.shape(matriz)

(1, 12)

In [25]:
print('La posicion del valor max es',arreglo.max) 

La posicion del valor max es <built-in method max of numpy.ndarray object at 0x0000028AB34E0CF0>
