In [2]:
import numpy as np

<h4 style = 'color:blue'>Generando un array de 12 elementos enteros con Random</h3> 

In [3]:
arreglo = np.random.randint(1,10,12)
arreglo

array([6, 5, 6, 3, 6, 8, 5, 9, 3, 8, 7, 7])

<h4 style = 'color:blue'>Obtener la dimension de un arreglo</h3>

In [4]:
np.shape(arreglo)

(12,)

<h4 style = 'color:blue'>Transformación del vector de 12 elemtnos a Matriz de 4x3 con Reshape</h3>

In [6]:
matriz = arreglo.reshape(4,3)
matriz

array([[6, 5, 6],
       [3, 6, 8],
       [5, 9, 3],
       [8, 7, 7]])

<h4 style = 'color:blue'>Tranformación del vector de 12 elementos a Matriz 4x3 con Reshape</h3>

In [7]:
np.shape(matriz)

(4, 3)

<h4 style = 'color:blue'>Otra tranformación del vector de 9 elementos a Matriz 3x4 con Reshape</h3>

In [8]:
matriz = arreglo.reshape(3,4)
matriz

array([[6, 5, 6, 3],
       [6, 8, 5, 9],
       [3, 8, 7, 7]])

<h4 style = 'color:blue'>Creando un Tensor</h3>

In [9]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]