##### **IMPORTANDO UNA LIBRERIA NUMPY** ######

In [12]:
import numpy as np

##### **CREANDO UNA LISTA DE 10 ELEMENTOS** ######

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### **TRANSFORMANDO LA LISTA A UN ARRAY** #####

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### **CORROBORANDO EL TIPO DE DATO** ###### 

In [8]:
type(arreglo)

numpy.ndarray

##### **CORROBORANDO EL TIPO DE DATO DE ARREGLO** #####

In [6]:
arreglo.dtype

dtype('int32')

##### **DEFINIENDO EL ARRAY DE int32 a float32** #####

In [7]:
np.array(arreglo, dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### **SIGUE SIENDO UN ARRA DE int32** #####

In [9]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### **TRANSFORMANDO DATOS DE int32 a float32** #####

In [10]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [11]:
arreglonew = np.arange(1,11,2)
arreglonew

array([1, 3, 5, 7, 9])

<h1 style = 'color:cyan'><b>ALGUNAS FUNCIONES DE NUMPY</b></h3>
<h4 style = 'color:aquamarine'>Obteniendo el promedio del array</h3>

In [14]:
promedio = np.mean(arreglo)
promedio

5.5

In [15]:
mediana = np.median(arreglo)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
desviacion_standard = np.std(arreglo)
desviacion_standard 

2.8722813232690143

In [17]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
arreglo_de_unos_2 = np.zeros(10)
arreglo_de_unos_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
arreglo_de_unos = arreglo_de_unos.astype(int)
arreglo_de_unos 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.63779266, 0.39764444, 0.18677524, 0.23217699, 0.42804788])

In [25]:
matriz = np.random.rand(3,3)
matriz

array([[0.32285247, 0.45984084, 0.42280043],
       [0.49570303, 0.94793919, 0.72930189],
       [0.92165947, 0.65427035, 0.09935185]])

In [ ]:
arreglo_aleatorio2 = np.random.randint(3,3,3)
arreglo_aleatorio2

In [32]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[59, 90, 86, 56, 37, 96, 65, 29, 45, 43, 78, 93, 43, 52, 55],
       [18, 83, 61, 51, 78,  4, 14, 59,  4, 40, 15, 16, 64, 94, 70],
       [24, 11, 65, 36, 65, 69, 66, 57, 58, 50, 24, 14, 15,  1, 43],
       [53, 76, 89, 49,  9, 11, 81, 91, 43, 28, 68, 36, 15, 57, 45],
       [ 8, 95, 24, 28, 86, 61, 81, 14, 19, 45, 14, 30,  3, 53, 80],
       [ 2, 62,  7, 35, 61, 85, 98, 61, 32, 58, 83, 23, 41, 83, 20],
       [29, 71, 41, 51, 41, 91, 97, 51, 30, 74, 67, 20, 53, 45, 87],
       [32, 28, 61, 40, 31, 88, 32, 71,  1,  5,  7, 18, 36, 72,  8],
       [13, 31, 26, 82, 65, 86, 93, 85, 13,  8, 44, 74, 90, 51, 81],
       [28, 89, 52, 71, 62, 25, 80, 40, 47, 70, 59, 69, 33, 44, 19],
       [65, 71, 26, 65, 44, 35,  8, 27, 16, 24, 42, 32, 62, 21, 86],
       [41, 94, 83, 93, 10,  7, 96, 32, 44, 22, 16, 78, 68, 44, 72],
       [59, 19, 63, 40, 47, 35, 33, 22, 21, 74, 58, 25, 20, 18, 46],
       [43, 35, 15,  2, 53, 47, 53,  2, 40, 93, 29,  7,  5, 25, 49],
       [79, 95, 46, 40, 63, 77, 34